### ISSUE TITLE
ShoppingFlowSpec.groovy and HomeSpec.groovy are failing

### ISSUE THREAD

**Issue by chavezom** [devops-dojo/the-app#15]
‌‌

**Comment by ojacques** [comment]
For me, only ShoppingFlowSpec is failing. HomeSpec is not.
With [this commit](https://github.com/devops-dojo/the-app/commit/b351fb9e1da6f393de2ff22a443bf9e3e7128b79) I added screenshots so that we can see what happened when the test fails.
And what I found is that at the time of the checkout, there is an error:
```
Last cause: Unable to find component with id 'discountSum' in [OrderItemListPanel [Component id = orderItems]]
	Expected: 'orderForm:orderItems:discountSum'.
	Found with similar names: ''

The problem is in "file:/var/lib/tomcat7/webapps/shop/WEB-INF/classes/io/github/zutherb/appstash/shop/ui/panel/OrderItemListPanel.html":
```

**Comment by chavezom** [comment]
Fixed
